### ISSUE TITLE
[webpack-isomorphic-tools] [error] asset not found: ./components/Layout/Layout.scss

### ISSUE THREAD

**Issue by ghost** [DremyGit/dremy-blog#1]
这是怎么回事？

**Comment by DremyGit** [comment]
@ziming2018 这是在执行什么命令的时候遇到的呢？直接使用 npm run build 命令看看能不能正常构建

**Comment by ghost** [comment]
@DremyGit 还是出现了如标题一样的错误，我用的是win7，在F盘下

**Comment by ghost** [comment]
@DremyGit README.md中没有搭建过程呀！

**Comment by ghost** [comment]
@DremyGit 为什么不搭理我了

**Comment by DremyGit** [comment]
根据你提供的信息，错误情况无法复现，建议更换 *nix 系统进行操作
