### ISSUE TITLE
能不能给个搭建过程？

### ISSUE THREAD

**Issue by ghost** [DremyGit/dremy-blog#2]
我想用你这个搭一个博客

**Comment by DremyGit** [comment]
本项目搭建的方式很简单， api、www 以及 manager 目录下是三个独立的项目。请分别参考每个 package.json 文件中的 script，并修改以下这些 config 配置文件后，即可完成搭建：

+ dremy-blog/api/config
+ dremy-blog/www/config.js
+ dremy-blog/manager/app/scripts/constants/config.default.js

由于本项目目前还有很多未完善之处，请勿用作除参考/学习以外的其它用途，谢谢。
